<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QuadraticPlacement.Core\QuadraticPlacement.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot" Version="5.1.58" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
